import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

const ALERT_RECIPIENTS = [
  'guilherme@latitude.sh',
  'ricardo.bortolansa@latitude.sh',
  'rafael.ribeiro@latitude.sh',
]

interface PriceChange {
  competitor: string
  productName: string
  cityName: string
  oldPrice: number
  newPrice: number
  changePercent: number
}

export async function sendPriceAlertEmail(priceChanges: PriceChange[]) {
  if (!process.env.RESEND_API_KEY) {
    console.log('RESEND_API_KEY not set, skipping email notification')
    console.log('Price changes that would have been reported:')
    priceChanges.forEach(change => {
      const direction = change.changePercent > 0 ? 'increased' : 'decreased'
      console.log(`  ${change.competitor} ${change.productName} (${change.cityName}): $${change.oldPrice} → $${change.newPrice} (${direction} ${Math.abs(change.changePercent).toFixed(1)}%)`)
    })
    return
  }

  const increases = priceChanges.filter(c => c.changePercent > 0)
  const decreases = priceChanges.filter(c => c.changePercent < 0)

  const formatChange = (change: PriceChange) => {
    const direction = change.changePercent > 0 ? '📈' : '📉'
    const color = change.changePercent > 0 ? '#dc2626' : '#16a34a'
    return `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${change.competitor}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${change.productName}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${change.cityName}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">$${change.oldPrice}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">$${change.newPrice}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; color: ${color}; font-weight: bold;">
          ${direction} ${change.changePercent > 0 ? '+' : ''}${change.changePercent.toFixed(1)}%
        </td>
      </tr>
    `
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
        table { border-collapse: collapse; width: 100%; margin: 16px 0; }
        th { background: #f3f4f6; padding: 12px 8px; text-align: left; border-bottom: 2px solid #e5e7eb; }
        h2 { color: #374151; margin-top: 24px; }
        .summary { background: #f9fafb; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
      </style>
    </head>
    <body>
      <h1>Competitor Price Alert</h1>

      <div class="summary">
        <p><strong>${priceChanges.length}</strong> competitor SKU(s) changed price by more than 10%:</p>
        <ul>
          ${increases.length > 0 ? `<li>📈 <strong>${increases.length}</strong> price increase(s)</li>` : ''}
          ${decreases.length > 0 ? `<li>📉 <strong>${decreases.length}</strong> price decrease(s)</li>` : ''}
        </ul>
      </div>

      ${increases.length > 0 ? `
        <h2>📈 Price Increases</h2>
        <table>
          <thead>
            <tr>
              <th>Competitor</th>
              <th>Product</th>
              <th>City</th>
              <th>Old Price</th>
              <th>New Price</th>
              <th>Change</th>
            </tr>
          </thead>
          <tbody>
            ${increases.map(formatChange).join('')}
          </tbody>
        </table>
      ` : ''}

      ${decreases.length > 0 ? `
        <h2>📉 Price Decreases</h2>
        <table>
          <thead>
            <tr>
              <th>Competitor</th>
              <th>Product</th>
              <th>City</th>
              <th>Old Price</th>
              <th>New Price</th>
              <th>Change</th>
            </tr>
          </thead>
          <tbody>
            ${decreases.map(formatChange).join('')}
          </tbody>
        </table>
      ` : ''}

      <p style="color: #6b7280; font-size: 14px; margin-top: 32px;">
        This alert was generated by the Latitude Pricing Tracker.<br>
        <a href="http://localhost:3000/comparisons">View Comparisons Dashboard</a>
      </p>
    </body>
    </html>
  `

  const textContent = priceChanges.map(change => {
    const direction = change.changePercent > 0 ? 'increased' : 'decreased'
    return `${change.competitor} ${change.productName} (${change.cityName}): $${change.oldPrice} → $${change.newPrice} (${direction} ${Math.abs(change.changePercent).toFixed(1)}%)`
  }).join('\n')

  try {
    const { data, error } = await resend.emails.send({
      from: 'Latitude Pricing Tracker <alerts@latitude.sh>',
      to: ALERT_RECIPIENTS,
      subject: `Price Alert: ${priceChanges.length} competitor SKU(s) changed by >10%`,
      html,
      text: `Competitor Price Alert\n\n${textContent}`,
    })

    if (error) {
      console.error('Failed to send email:', error)
      return
    }

    console.log(`Email sent successfully to ${ALERT_RECIPIENTS.join(', ')}`)
    console.log('Email ID:', data?.id)
  } catch (error) {
    console.error('Failed to send email:', error)
  }
}
